version: "3"

services:
  tailscale:
    container_name: tailscale-container
    build:
      context: ./build
      dockerfile: Dockerfile
    environment:
      - SECRET_AUTH_KEY
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    image: tailscale:0.3
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    
