name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./build --file build/Dockerfile --tag pi-tailscale:$(date +%s) --build-arg secret_auth_key=${{ secrets.TAILSCALE_AUTH_KEY }}
